const marketData = [
  // ================= Commodities =================
  {
    id: 1,
    name: "Gold",
    code: "XAUUSD",
    symbol: "OANDA:XAU_USD",
    category: "Commodities",
    provider: "twelvedata",
    icon: "/icons/gold.png",
    exchange: "OANDA",
    decimals: 2,
  },
  {
    id: 2,
    name: "Silver",
    code: "XAGUSD",
    symbol: "OANDA:XAG_USD",
    category: "Commodities",
    provider: "twelvedata",
    icon: "/icons/silver.png",
    exchange: "OANDA",
    decimals: 2,
  },

  // ================= Crypto =================
  {
    id: 3,
    name: "Bitcoin",
    code: "BTCUSDT",
    symbol: "BTCUSDT",
    category: "Crypto",
    provider: "binance",
    icon: "/icons/btc.png",
    exchange: "Binance",
    decimals: 2,
  },
  {
    id: 4,
    name: "Ethereum",
    code: "ETHUSDT",
    symbol: "ETHUSDT",
    category: "Crypto",
    provider: "binance",
    icon: "/icons/eth.png",
    exchange: "Binance",
    decimals: 2,
  },
  {
    id: 5,
    name: "BNB",
    code: "BNBUSDT",
    symbol: "BNBUSDT",
    category: "Crypto",
    provider: "binance",
    icon: "/icons/bnb.png",
    exchange: "Binance",
    decimals: 2,
  },
  {
    id: 6,
    name: "Solana",
    code: "SOLUSDT",
    symbol: "SOLUSDT",
    category: "Crypto",
    provider: "binance",
    icon: "/icons/sol.png",
    exchange: "Binance",
    decimals: 2,
  },
  {
    id: 7,
    name: "Dogecoin",
    code: "DOGEUSDT",
    symbol: "DOGEUSDT",
    category: "Crypto",
    provider: "binance",
    icon: "/icons/doge.png",
    exchange: "Binance",
    decimals: 5,
  },
  {
    id: 8,
    name: "Cardano",
    code: "ADAUSDT",
    symbol: "ADAUSDT",
    category: "Crypto",
    provider: "binance",
    icon: "/icons/ada.png",
    exchange: "Binance",
    decimals: 5,
  },
  {
    id: 9,
    name: "Ripple",
    code: "XRPUSDT",
    symbol: "XRPUSDT",
    category: "Crypto",
    provider: "binance",
    icon: "/icons/xrp.png",
    exchange: "Binance",
    decimals: 5,
  },
  {
    id: 10,
    name: "Sui",
    code: "SUIUSDT",
    symbol: "SUIUSDT",
    category: "Crypto",
    provider: "binance",
    icon: "/icons/sui.png",
    exchange: "Binance",
    decimals: 4,
  },

  // ================= Forex =================
  {
    id: 11,
    name: "EUR/USD",
    code: "EURUSD",
    symbol: "OANDA:EUR_USD",
    category: "Forex",
    provider: "twelvedata",
    icon: "/icons/eurusd.png",
    exchange: "OANDA",
    decimals: 5,
  },
  {
    id: 12,
    name: "GBP/USD",
    code: "GBPUSD",
    symbol: "OANDA:GBP_USD",
    category: "Forex",
    provider: "twelvedata",
    icon: "/icons/gbpusd.png",
    exchange: "OANDA",
    decimals: 5,
  },
  {
    id: 13,
    name: "USD/JPY",
    code: "USDJPY",
    symbol: "OANDA:USD_JPY",
    category: "Forex",
    provider: "twelvedata",
    icon: "/icons/usdjpy.png",
    exchange: "OANDA",
    decimals: 3,
  },

  // ================= Stocks =================
  {
    id: 14,
    name: "Apple",
    code: "AAPL",
    symbol: "AAPL",
    category: "Stocks",
    provider: "twelvedata",
    icon: "/icons/apple.png",
    exchange: "NASDAQ",
    decimals: 2,
  },
  {
    id: 15,
    name: "Tesla",
    code: "TSLA",
    symbol: "TSLA",
    category: "Stocks",
    provider: "twelvedata",
    icon: "/icons/tesla.png",
    exchange: "NASDAQ",
    decimals: 2,
  },
  {
    id: 16,
    name: "Amazon",
    code: "AMZN",
    symbol: "AMZN",
    category: "Stocks",
    provider: "twelvedata",
    icon: "/icons/amazon.png",
    exchange: "NASDAQ",
    decimals: 2,
  },
  {
    id: 17,
    name: "Nvidia",
    code: "NVDA",
    symbol: "NVDA",
    category: "Stocks",
    provider: "twelvedata",
    icon: "/icons/nvidia.png",
    exchange: "NASDAQ",
    decimals: 2,
  },

  // ================= Indices =================
  {
    id: 18,
    name: "S&P500",
    code: "SPX500",
    symbol: "OANDA:SPX500_USD",
    category: "Indices",
    provider: "twelvedata",
    icon: "/icons/sp500.png",
    exchange: "OANDA",
    decimals: 2,
  },
  {
    id: 19,
    name: "NASDAQ100",
    code: "NAS100",
    symbol: "OANDA:NAS100_USD",
    category: "Indices",
    provider: "twelvedata",
    icon: "/icons/nas100.png",
    exchange: "OANDA",
    decimals: 2,
  },
];

export default marketData;
